language: node_js
node_js:
   - 8
cache:
  yarn: true
  directories:
  - $HOME/.npm
script:
  - npm test
deploy:
    provider: script
    skip_cleanup: true
    script: bash scripts/Deploy.sh
    on:
      branch: master
