language: node_js
node_js:
   - Carbon
cache:
  yarn: true
  directories:
  - $HOME/.npm
script:
  - npm test
deploy:
    provider: script
    script: bash scripts/Deploy.sh
    on:
      branch: master
