language: node_js
node_js:
   - stable
cache:
  yarn: true
  directories:
  - $HOME/.npm
script:
  - npm test
deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/Deploy.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: bash scripts/Deploy.sh
    on:
      branch: develop
